# Generated by Django 3.1.3 on 2020-11-13 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loaner_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='loaner',
            table='loaner',
        ),
    ]
